analytics: {}
color:
  brandColors:
    - '#C8C8B0'
    - '#081840'
    - '#9060A8'
    - '#D8B818'
    - '#C8B8F0'
  brandStrength: 0
  lightness: 0.792792
  rhythmicContrast: 0.490991
  saturation: 0.434684
cta: {}
layout_spectrum: 0.689189
name: jwren
opengraph: {}
purpose: {}
typography_spectrum: 0.516891
