name: jwren
favicon: null
layout_spectrum: 0.41556
typography_spectrum: 0.516891
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#151515'
    - '#a9a9a9'
    - '#6c6c6c'
    - '#dfdfdf'
  brandStrength: 0
  lightness: 0.9375
  saturation: 0.5
  rhythmicContrast: 0.25
purpose:
  - name: null
    item: null
    url: null
