typography_spectrum: 0.516891
color:
  brandColors:
    - '#edd9d8'
    - '#1f3121'
    - '#74704b'
    - '#e27368'
    - '#cc4132'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.08354952232912183
analytics:
  google: null
  facebook: null
  twitter: null
author:
  email: j.wren.art@gmail.com
name: jwren
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose:
  - name: null
    item: null
    url: null
